### ISSUE TITLE
Integration tests not working on local

### ISSUE THREAD

**Issue by jgraham0325** [CJSCommonPlatform/artemis-manager#6]
Hi,

I've checked out the repo and tried to do a build but it's failing at integration test stage.

Steps to reproduce:
run from command line: mvn clean install

Output:
`
INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
server-out:     _        _               _
server-out:    / \  ____| |_  ___ __  __(_) _____
server-out:   / _ \|  _ \ __|/ _ \  \/  | |/  __/
server-out:  / ___ \ | \/ |_/  __/ |\/| | |\___ \
server-out: /_/   \_\|   \__\____|_|  |_|_|/___ /
server-out: Apache ActiveMQ Artemis 1.5.5
server-out:
server-out:
server-out:12:56:05,132 INFO  [org.apache.activemq.artemis.integration.bootstrap] AMQ101000: Starting ActiveMQ Artemis Server
server-out:12:56:05,218 INFO  [org.apache.activemq.artemis.core.server] AMQ221000: live Message Broker is starting with configuration Broker Configuration (clustered=false,journalDirectory=./data/journal,bindingsDirectory=./data/bindings,largeMessagesDirectory=./data/large-messages,pagingDirectory=./data/paging)
server-out:12:56:05,334 INFO  [org.apache.activemq.artemis.core.server] AMQ221013: Using NIO Journal
server-out:12:56:05,530 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-server]. Adding protocol support for: CORE
server-out:12:56:05,534 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-amqp-protocol]. Adding protocol support for: AMQP
server-out:12:56:05,538 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-hornetq-protocol]. Adding protocol support for: HORNETQ
server-out:12:56:05,541 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-mqtt-protocol]. Adding protocol support for: MQTT
server-out:12:56:05,562 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-openwire-protocol]. Adding protocol support for: OPENWIRE
server-out:12:56:05,643 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-stomp-protocol]. Adding protocol support for: STOMP
[INFO] Running uk.gov.justice.artemis.manager.ArtemisManagerIT
server-out:12:56:06,304 INFO  [org.apache.activemq.artemis.core.server] AMQ221003: Deploying queue jms.queue.DLQ
server-out:12:56:06,378 INFO  [org.apache.activemq.artemis.core.server] AMQ221003: Deploying queue jms.queue.ExpiryQueue
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/jamesg/app/artemis-manager/target/artemis-manager.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/jamesg/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/jamesg/.m2/repository/org/slf4j/slf4j-simple/1.7.10/slf4j-simple-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
server-out:12:56:08,126 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:61616 for protocols [CORE,MQTT,AMQP,STOMP,HORNETQ,OPENWIRE]
server-out:12:56:08,130 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:5445 for protocols [HORNETQ,STOMP]
server-out:12:56:08,133 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:5672 for protocols [AMQP]
server-out:12:56:08,139 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:1883 for protocols [MQTT]
server-out:12:56:08,145 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:61613 for protocols [STOMP]
server-out:12:56:08,153 INFO  [org.apache.activemq.artemis.core.server] AMQ221007: Server is now live
server-out:12:56:08,153 INFO  [org.apache.activemq.artemis.core.server] AMQ221001: Apache ActiveMQ Artemis Message Broker version 1.5.5 [0.0.0.0, nodeID=b58e3cb6-64c6-11e8-b28b-4c327596745d] 
[ERROR] Tests run: 11, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 44.071 s <<< FAILURE! - in uk.gov.justice.artemis.manager.ArtemisManagerIT
[ERROR] shouldReprocessLargeMessageOntoOriginalQueue(uk.gov.justice.artemis.manager.ArtemisManagerIT)  Time elapsed: 6.004 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "{\"Command\":\"Reprocess message\",\"Occurrences\":2}\n"
     but: was "{\"Command\":\"Reprocess message\",\"Occurrences\":0}\n"
        at uk.gov.justice.artemis.manager.ArtemisManagerIT.shouldReprocessLargeMessageOntoOriginalQueue(ArtemisManagerIT.java:225)

[ERROR] shouldIgnoreUnknownMessageIds(uk.gov.justice.artemis.manager.ArtemisManagerIT)  Time elapsed: 7.301 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is json with json path "$..['msgId']" evaluated to a collection with size <1>
     but: json path "$..['msgId']" was evaluated to <["9fc93d54-64c9-11e8-b4db-4c327596745d","9fc9d995-64c9-11e8-b4db-4c327596745d"]>
        at uk.gov.justice.artemis.manager.ArtemisManagerIT.shouldIgnoreUnknownMessageIds(ArtemisManagerIT.java:155)

`

Anyone have any ideas?

**Comment by jgraham0325** [comment]
Was due to conflicting port used by Vagrant. Shutting down Vagrant should solve the problem
